# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check config file for CloudFormation
      uses: minchao/cfn-nag-action@master
      with:
        args: '--input-path ecs-cluster.yaml'
