name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      with:
        image: antoineguillard/action-webserver
        tag: latest
        registry: https://hub.docker.com/u/antoineguillard
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
     # run: docker build . --file Dockerfile --tag webserver-action:$(date +%s)
